require 'rake_ext'

project \
  name: "validatable2",
  # version: '0.1.0',
  gem: true,
  summary: "Validations for Ruby objects",

  author: "Alexey Petrushin",
  homepage: "http://github.com/alexeypetrushin/validatable2"

$LOAD_PATH << "#{File.dirname __FILE__}/lib"

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.ruby_opts << '-rubygems'
  test.pattern = 'test/**/test_*.rb'
  # test.pattern = 'test/**/unit/test_validates_true_for.rb'
  test.verbose = true
end

task :default => :test