+port: 3000

+master_domain: localhost
+master_email: support@localhost



+logo: saas4b

+session_key: saas4b_development
+session_secret: "very very very very very very very very very very very very secret code"

+default_path: /sm/

app_port: 3001
service_mix_port: 3000

+default_language: en

services:
  spaces:
    callbacks: "http://localhost:3001/wigets_callbacks"
    
+max_file_size: 1048576 # 1 Mb
+max_account_files_size: 5368709120 # 5 Gb

available_themes:
- default
- simple_organization