layout_template: default
slots:
  top_panel: "/kit/top_panel"
  navigation: "/kit/navigation"
  bottom_aspects:
  - "/kit/aspects/comments"
  tools:
  - "/tools/buttons"
  - "/tools/search"
  - "/tools/tags"
  - "/tools/access"
  - "/tools/context_menu"
  bottom_panel: "/kit/bottom_panel"