# https://github.com/jashkenas/coffee-script/wiki/[HowTo]-Compiling-and-Setting-Up-Build-Tools

task 'watch', 'Watch for changes and compile CoffeeScript sources to JavaScript', ->
  console.dir require('child_process')
  {exec} = require 'child_process'
  exec 'coffee --watch --compile --output built/js/ app/', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr