SPEC_DIR = File.dirname __FILE__

require "#{SPEC_DIR}/ArraySpec"
require "#{SPEC_DIR}/AssertSpec"
require "#{SPEC_DIR}/CacheSpec"
require "#{SPEC_DIR}/ClassLoaderSpec"
require "#{SPEC_DIR}/ImportAllSpec"
require "#{SPEC_DIR}/KernelSpec"
require "#{SPEC_DIR}/LocalizationSpec"
require "#{SPEC_DIR}/ModuleSpec"
require "#{SPEC_DIR}/ObjectSpec"
require "#{SPEC_DIR}/ObservableSpec"
require "#{SPEC_DIR}/OpenConstructorSpec"
require "#{SPEC_DIR}/PathSpec"
require "#{SPEC_DIR}/ResourceSpec"
require "#{SPEC_DIR}/StateMachineSpec"
require "#{SPEC_DIR}/SynchronizerSpec"
