require 'rake_ext'

project(
  name: "store",
  official_name: "rad_store",
  summary: "Simple Store",
  dirs: ['app', 'config'],
  gem: true,

  author: "Alexey Petrushin",
  homepage: "http://github.com/alexeypetrushin/rad_store"
)